In [1]:
import functions.normal.BB as BB
import functions.cython.BB as c_BB
import numpy as np

In [2]:
W1 = np.array([0,0,0,0,0,0])
W2 = np.array([0,0,0,0,0,0])
W3 = np.array([0,0,0,0,0,0])
W4 = np.array([0,0,0,0,0,0])
TDS = 300
LStar = np.array([1,1,1,1,1,1])
eta = 0.9

## W1

In [23]:
%%timeit -n1 -r5
print(BB.W1_DS(W1,TDS,LStar,eta))

[2.44003339 2.44003339 2.44003339 2.44003339 2.44003339 2.44003339]
[2.44003339 2.44003339 2.44003339 2.44003339 2.44003339 2.44003339]
[2.44003339 2.44003339 2.44003339 2.44003339 2.44003339 2.44003339]
[2.44003339 2.44003339 2.44003339 2.44003339 2.44003339 2.44003339]
[2.44003339 2.44003339 2.44003339 2.44003339 2.44003339 2.44003339]
849 µs ± 233 µs per loop (mean ± std. dev. of 5 runs, 1 loop each)


In [24]:
%%timeit -n1 -r5
print(c_BB.W1_DS(W1,TDS,LStar,eta))

[2.44003314 2.44003314 2.44003314 2.44003314 2.44003314 2.44003314]
[2.44003314 2.44003314 2.44003314 2.44003314 2.44003314 2.44003314]
[2.44003314 2.44003314 2.44003314 2.44003314 2.44003314 2.44003314]
[2.44003314 2.44003314 2.44003314 2.44003314 2.44003314 2.44003314]
[2.44003314 2.44003314 2.44003314 2.44003314 2.44003314 2.44003314]
1.09 ms ± 428 µs per loop (mean ± std. dev. of 5 runs, 1 loop each)


## W2

In [13]:
%%timeit -n1 -r5
print(BB.W2_DS(W2,TDS,LStar,eta))

[1.47284467 1.47284467 1.47284467 1.47284467 1.47284467 1.47284467]
[1.47284467 1.47284467 1.47284467 1.47284467 1.47284467 1.47284467]
[1.47284467 1.47284467 1.47284467 1.47284467 1.47284467 1.47284467]
[1.47284467 1.47284467 1.47284467 1.47284467 1.47284467 1.47284467]
[1.47284467 1.47284467 1.47284467 1.47284467 1.47284467 1.47284467]
787 µs ± 106 µs per loop (mean ± std. dev. of 5 runs, 1 loop each)


In [14]:
%%timeit -n1 -r5
print(c_BB.W2_DS(W2,TDS,LStar,eta))

[1.47284459 1.47284459 1.47284459 1.47284459 1.47284459 1.47284459]
[1.47284459 1.47284459 1.47284459 1.47284459 1.47284459 1.47284459]
[1.47284459 1.47284459 1.47284459 1.47284459 1.47284459 1.47284459]
[1.47284459 1.47284459 1.47284459 1.47284459 1.47284459 1.47284459]
[1.47284459 1.47284459 1.47284459 1.47284459 1.47284459 1.47284459]
1.15 ms ± 482 µs per loop (mean ± std. dev. of 5 runs, 1 loop each)


## W3

In [15]:
%%timeit -n1 -r5
print(BB.W3_DS(W3,TDS,LStar,eta))

[-3.50259293 -3.50259293 -3.50259293 -3.50259293 -3.50259293 -3.50259293]
[-3.50259293 -3.50259293 -3.50259293 -3.50259293 -3.50259293 -3.50259293]
[-3.50259293 -3.50259293 -3.50259293 -3.50259293 -3.50259293 -3.50259293]
[-3.50259293 -3.50259293 -3.50259293 -3.50259293 -3.50259293 -3.50259293]
[-3.50259293 -3.50259293 -3.50259293 -3.50259293 -3.50259293 -3.50259293]
745 µs ± 146 µs per loop (mean ± std. dev. of 5 runs, 1 loop each)


In [16]:
%%timeit -n1 -r5
print(c_BB.W3_DS(W3,TDS,LStar,eta))

[-3.50259291 -3.50259291 -3.50259291 -3.50259291 -3.50259291 -3.50259291]
[-3.50259291 -3.50259291 -3.50259291 -3.50259291 -3.50259291 -3.50259291]
[-3.50259291 -3.50259291 -3.50259291 -3.50259291 -3.50259291 -3.50259291]
[-3.50259291 -3.50259291 -3.50259291 -3.50259291 -3.50259291 -3.50259291]
[-3.50259291 -3.50259291 -3.50259291 -3.50259291 -3.50259291 -3.50259291]
864 µs ± 293 µs per loop (mean ± std. dev. of 5 runs, 1 loop each)


## W4

In [17]:
%%timeit -n1 -r5
print(BB.W4_DS(W3,TDS,LStar,eta))

[-5.14894029 -5.14894029 -5.14894029 -5.14894029 -5.14894029 -5.14894029]
[-5.14894029 -5.14894029 -5.14894029 -5.14894029 -5.14894029 -5.14894029]
[-5.14894029 -5.14894029 -5.14894029 -5.14894029 -5.14894029 -5.14894029]
[-5.14894029 -5.14894029 -5.14894029 -5.14894029 -5.14894029 -5.14894029]
[-5.14894029 -5.14894029 -5.14894029 -5.14894029 -5.14894029 -5.14894029]
777 µs ± 139 µs per loop (mean ± std. dev. of 5 runs, 1 loop each)


In [18]:
%%timeit -n1 -r5
print(c_BB.W4_DS(W3,TDS,LStar,eta))

[-5.14894026 -5.14894026 -5.14894026 -5.14894026 -5.14894026 -5.14894026]
[-5.14894026 -5.14894026 -5.14894026 -5.14894026 -5.14894026 -5.14894026]
[-5.14894026 -5.14894026 -5.14894026 -5.14894026 -5.14894026 -5.14894026]
[-5.14894026 -5.14894026 -5.14894026 -5.14894026 -5.14894026 -5.14894026]
[-5.14894026 -5.14894026 -5.14894026 -5.14894026 -5.14894026 -5.14894026]
762 µs ± 155 µs per loop (mean ± std. dev. of 5 runs, 1 loop each)
